

module.exports = [ 
    {
      id: 1,
      image: "./assets/shaw.png",
      company: "Shaw Academy",
      position: "UX Designer for Product Based Company",
      responsiveRecruiter: false,
      remoteWorkAvailable: true,
      type: "Full time",
      salary: "₹1,500,000",
      YOE: "2-3",
      specification: [
        "Communicate effectively in a cross-functional product development team",
        "Present ideas and designs effectively",
      ],
      numberOfApplicants: 14,
      timePosted: "45 mins",
    },
    {
      id: 2,
      image: "./assets/google.png",
      company: "Truecaller",
      position: "Product Designer",
      responsiveRecruiter: false,
      remoteWorkAvailable: false,
      type: "Full time",
      salary: "Undisclosed",
      YOE: "1+",
      specification: [
        "Establish creative direction and develop concepts together with the product team.",
        "Help developers and visual designers with solving design challenges and ...",
      ],
      numberOfApplicants: 82,
      timePosted: "2 days",
    },
    {
      id: 3,
      image: "./assets/truecaller.png",
      company: "Google India",
      position: "Product Lead",
      responsiveRecruiter: true,
      remoteWorkAvailable: false,
      type: "Full time",
      salary: "Undisclosed",
      YOE: "10+",
      specification: [
        "Experience in product management or design in internet products and technologies",
        "Synthesis and drive product strategy from interaction with customers ...",
      ],
      numberOfApplicants: 104,
      timePosted: "20 days",
    },
    {
      id: 4,
      image: "./assets/vmware.png",
      company: "VMWare",
      position: "UX Designer for Product Based Company",
      responsiveRecruiter: true,
      remoteWorkAvailable: true,
      type: "Part-time",
      salary: "Undisclosed",
      YOE: "2-3",
      specification: [
        "Closely collaborate with the product management and engineering team to identify product goals and vision",
        "You will build intuitive, beautiful and meaningful",
      ],
      numberOfApplicants: 20,
      timePosted: "5 days",
    },
    {
      id: 5,
      image: './assets/wwurfel.png',
      company: "Wurfel Kuche Pvt. Ltd",
      position: "Product Designer",
      responsiveRecruiter: false,
      remoteWorkAvailable: true,
      type: "Full time, Contract",
      salary: "₹4,000,000 - 5,000,000",
      YOE: "2-3",
      specification: [
        "Identifying opportunities for new products.",
        "Design new products related to interior industry.",
      ],
      numberOfApplicants: 5,
      timePosted: "7 hours",
    },
  ];